title = "Midas"  # From Git
organizationName = "nightcycle"
gitRepoUrl = "https://github.com/nightcycle/midas" # From Git
gitSourceBranch = "master"
projectName = "midas"
url = "https://nightcycle.github.io"
baseUrl = "/midas/"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"
tagline = "An analytics framework to turn every game you touch to gold."

[home]
enabled = true
includeReadme = true

[footer]
style = "dark"
copyright = "Copyright © 2022 Nightcycle Studios. Built with Moonwave and Docusaurus"


[[home.features]]
title = "Decentralized"
description = "Empowers you to track state where it's being used."

[[home.features]]
title = "Organized"
description = "Stores state in flexible and navigable hierarchies."

[[home.features]]
title = "Efficient"
description = "Endeavors to allow you to store as much information as you want."