title = "midas"  # From Git
gitRepoUrl = "https://github.com/nightcycle/midas" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/"

# From git:
organizationName = "nightcycle"
projectName = "midas"
url = "https://nightcycle.github.io"
baseUrl = "/midas/"
tagline = "the ultimate Roblox analytics suite"

[footer]
style = "dark"
copyright = "Copyright © 2022 Nightcycle Studios. Built with Moonwave and Docusaurus"
